rvm: 2.0.0
env:
- PUPPET_VERSION=2.7.25
- PUPPET_VERSION=3.0.2
- PUPPET_VERSION=3.1.1
- PUPPET_VERSION=3.2.4
- PUPPET_VERSION=3.3.2
- PUPPET_VERSION=3.4.3
- PUPPET_VERSION=3.5.1
- PUPPET_VERSION=3.6.2
- PUPPET_VERSION=3.7.5
- PUPPET_VERSION=4.8.1
notifications:
  email: false
  hipchat:
    rooms:
      secure: NwtA7o8QbeACbEqfDV4t9FQiVHXuCXuaLJKKKu++0F2xzFMqZJPG0rQiwYZXQhqZRMOSYV0DPdpXhGI5T95dSHbbXIzrzeDAcxP6CDCXhGzmhdXBe2jCh72cHPmTTI/thkrM3Oz/i6pUIN54g7ug3Ve3Lk1IdwoSHHYih1yyMZ5g6gf8PASrdY7h11Z1lEymGKMX/sk6b4YKLgIsGmN4oAU0AD3Ib8xMKILcWrRZHAp3tB3L8UlQHeocy2nBdg89m+E5d1t3DgLBFnNMmcFMuDsybCfGDp1nwYSRLOVy4R786nb4yvCcnm737dPdeEhVkSJQi66sv9hA4mUMwgluUEHEPuh++6dT/WU5vwBSHWIBqnFE+elyClSGw/glhqlDAfirp6t72AhQUTyLH95gYwD/GLpwqvNagmm+ptl5IeAuq/u45texQPmIFEMDy7gzkr9sjSIlTn5D8tT0uXwHeZmKM0KZIeF3vtuQYf36qxxyauq2cRo+nqr63megJZnt+iwU+guyBB5JmKBxrjnqFdBrvwN0RX6h4pmy2wUcDADnKd7uF7aueIWN2x/Q8AhppU5AyxKJWWs/YBPFdOoSlXQVhW+GMFEMNdoMepQJh/DGMtd5sysDSziRAjEH9zBxD5dYHcbw5FqUnuh0+mulTjzuIT++jvKLQ4IBdRjLpjI=
    template:
    - 'Puppet Module - %{repository} #%{build_number} (%{build_url}) by %{author}:
      %{message}'
branches:
  only:
  - master
